//  TYPES HERE
export const SET_LOADING = 'SET_LOADING';   

export const SET_COUNTRY = 'SET_COUNTRY';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const HANDLE_INPUT_ON_CHANGE = 'HANDLE_INPUT_ON_CHANGE';
export const HANDLE_SELECT_COUNTRY = 'HANDLE_SELECT_COUNTRY';
export const CLEAR_AUTH = 'CLEAR_AUTH';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
